language: node_js
node_js:
  - "8"
branches:
  only:
    - master
install:
  # Install React Native, Yarn and Yeoman:
  - npm install
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
